### ISSUE TITLE
No Thumbnail while Searching

### ISSUE THREAD

**Issue by Norman191** [balvinderz/animewatcher#1]
.

**Comment by balvinderz** [comment]
I will try to implement the 1st one.
For 2nd how can  where should i send you the project (without androidx migration).

**Comment by kiloma** [comment]
Thank you for responding, 

About the **AndroidX** i managed to revert the project to the normal state with success.

All i need now is the Thumbnail when searching in the Json in raw folder.
> Can you add the image to json file (when the user search for the names) he also sees the anime image.

If you had time and  made it happen

Or just reply here.
**Thank you** again

**Comment by balvinderz** [comment]
I implemented the 1st one .
You can check the json file if you want .
Tell me if you want any changes.

**Comment by kiloma** [comment]
Thank you so much.
It's working great

**Comment by kiloma** [comment]
After seeing many other Apps, i think this App needs :

1. A favorite ( fragment or activity ) so the user can choose his best episodes and also going to ( help him remember ) his last watched episode, so he can continue from there.
2. A ( fragment or activity ) only for anime **_MOVIES_**, to be easier to locate and watch them, instead of keep looking for them among the animes that have episodes.
3. User can choose animes to watch later and list them in a ( fragment or activity ) .

These will make this App the best .

**Comment by balvinderz** [comment]
I will try to implement those feautures after some time .Probably after 10-15 days.
Thank you for the suggestions :)

**Comment by Devilemox** [comment]
Its still not working ... No thumbnail appears for me either ... 
Not even on recommended animes 😅
